### ISSUE TITLE
[EPIC]

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/RaidOrganizer#1]
Raid Organizer feature

- [ ] Create a raidgroup
- [ ] Add members to raidgroup
- [ ] Create a raidevent
- [ ] Let registered members sign up to a raid event
- [ ] Raid roles and classes?
...
